name: Draft PDF for new JOSS paper

on:
  push:
    paths:
      - 'joss/in_preparation/river_temperature_dynamics/**'
      - '.github/workflows/draft-pdf.yml'

# ADD THIS BLOCK TO GRANT WRITE ACCESS:
permissions:
  contents: write

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: joss/in_preparation/river_temperature_dynamics/paper.md
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: joss/in_preparation/river_temperature_dynamics/paper.pdf

      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Paper PDF Draft for RiverTemperatureDynamics'
          add: 'joss/in_preparation/river_temperature_dynamics/paper.pdf'
